name: Issue Comment

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  lights:
    runs-on: pizero
      
    steps:
    - run: |
        echo "Comment left on an issue: ${{ github.event.comment.body }}"
  
    - run: |
        comment="${{ github.event.comment.body }}"
        light_colour=$(echo $comment | grep -Po '(\#[0-9a-fA-F]{6})' || true)
        light_colour_len=${#light_colour}
        if [ $light_colour_len = 7 ]; then echo "::set-output name=light_colour::$light_colour"; else echo "::set-output name=light_colour::#ffffff"; fi
      id: set_light_colour
      name: Get color
    
    - run: python3 ${GITHUB_WORKSPACE}/color.py "${{ steps.set_light_colour.outputs.light_colour }}" &
      if: ${{ github.event_name == 'issue_comment' }}

    - run: python3 ${GITHUB_WORKSPACE}/color.py "#000000" &
      if: ${{ github.event_name == 'workflow_dispatch' }}
